server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarymanagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: taro
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    com.com.Solo: DEBUG
